import type { Metadata } from "next";
import Providers from "./providers";
import "./globals.css";
import DefaultLayout from "@/components/layouts/DefaultLayout";
import { GoogleTagManager } from "@next/third-parties/google";
import GAPageView from "@/components/google-analytic/GAPageView";

export interface RootLayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "KITTIPAT | RESUME",
  description: "Generated by create next app",
};

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <GoogleTagManager gtmId="G-KH1DE7Y5FD" />
        <GAPageView />
        <Providers>
          <DefaultLayout>{children}</DefaultLayout>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
