import "./globals.css";

import type { Metadata } from "next";

import DefaultLayout from "@/components/layouts/DefaultLayout";

import Providers from "./providers";

export interface RootLayoutProps {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "KITTIPAT | RESUME",
  description: "Generated by create next app",
};

const RootLayout: React.FC<RootLayoutProps> = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning>
        <Providers>
          <DefaultLayout>{children}</DefaultLayout>
        </Providers>
      </body>
    </html>
  );
};

export default RootLayout;
